"""add time_updated migration

Revision ID: a58d39783aa6
Revises: a3c9e7455486
Create Date: 2023-03-04 13:37:34.999407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58d39783aa6'
down_revision = 'a3c9e7455486'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('time_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('prescription', sa.Column('time_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescription', 'time_updated')
    op.drop_column('patient', 'time_updated')
    # ### end Alembic commands ###
