version: '3.8'

services:
  order-service-db: 
    image: postgres:15-alpine
    ports: 
      - 5433:5432
    env_file:
      - order-service/.env
  patient-service-db:
    image: postgres:15-alpine
    ports: 
      - 5432:5432
    env_file:
      - patient-service/.env
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - order-service-db
      - patient-service-db
